// Compile-time model-catalog generation.
//
// Reads the checked-in `models.json` and emits a `builtin_models()` function
// (into OUT_DIR) returning `agent_core::types::Model` literals. The Rust
// equivalent of pi-mono's `models.generated.ts`: the catalog data is
// reviewable JSON, and the generated code is regenerated whenever it changes.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use serde::Deserialize;

// Local mirror of the catalog shape — build scripts can't depend on
// `agent-core`, so the schema is declared inline. Field names match the JSON
// wire names; serde defaults keep optional fields optional.
#[derive(Deserialize)]
struct CatalogModel {
    id: String,
    name: String,
    api: String,
    provider: String,
    #[serde(rename = "baseUrl")]
    base_url: String,
    reasoning: bool,
    input: Vec<String>,
    cost: CatalogCost,
    #[serde(rename = "contextWindow")]
    context_window: u64,
    #[serde(rename = "maxTokens")]
    max_tokens: u64,
    #[serde(default)]
    compat: CatalogCompat,
}

#[derive(Deserialize)]
struct CatalogCost {
    input: f64,
    output: f64,
    #[serde(rename = "cacheRead")]
    cache_read: f64,
    #[serde(rename = "cacheWrite")]
    cache_write: f64,
}

#[derive(Deserialize, Default)]
struct CatalogCompat {
    #[serde(rename = "forceAdaptiveThinking")]
    force_adaptive_thinking: Option<bool>,
    #[serde(rename = "supportsTemperature")]
    supports_temperature: Option<bool>,
}

fn api_variant(api: &str) -> &'static str {
    match api {
        "anthropic" => "agent_core::types::Api::Anthropic",
        "openai" => "agent_core::types::Api::Openai",
        "openai-responses" => "agent_core::types::Api::OpenaiResponses",
        "mock" => "agent_core::types::Api::Mock",
        other => panic!("models.json: unknown api {other:?}"),
    }
}

fn opt_bool(value: Option<bool>) -> String {
    match value {
        Some(b) => format!("Some({b})"),
        None => "None".to_string(),
    }
}

fn main() {
    println!("cargo:rerun-if-changed=models.json");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let json_path = Path::new(&manifest_dir).join("models.json");
    let raw = fs::read_to_string(&json_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", json_path.display()));
    let models: Vec<CatalogModel> = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("parse models.json: {e}"));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from models.json — do not edit.\n");
    out.push_str("#[allow(clippy::all)]\n");
    out.push_str("pub fn builtin_models() -> Vec<agent_core::types::Model> {\n");
    out.push_str("    vec![\n");
    for m in &models {
        let inputs = m
            .input
            .iter()
            .map(|s| format!("{s:?}.into()"))
            .collect::<Vec<_>>()
            .join(", ");
        write!(
            out,
            "        agent_core::types::Model {{\n\
             \x20            id: {id:?}.into(),\n\
             \x20            name: {name:?}.into(),\n\
             \x20            api: {api},\n\
             \x20            provider: {provider:?}.into(),\n\
             \x20            base_url: {base_url:?}.into(),\n\
             \x20            reasoning: {reasoning},\n\
             \x20            input: vec![{inputs}],\n\
             \x20            cost: agent_core::types::ModelCost {{ input: {ci:?}, output: {co:?}, cache_read: {cr:?}, cache_write: {cw:?} }},\n\
             \x20            context_window: {ctx},\n\
             \x20            max_tokens: {max},\n\
             \x20            compat: agent_core::types::ModelCompat {{ force_adaptive_thinking: {fat}, supports_temperature: {st} }},\n\
             \x20        }},\n",
            id = m.id,
            name = m.name,
            api = api_variant(&m.api),
            provider = m.provider,
            base_url = m.base_url,
            reasoning = m.reasoning,
            inputs = inputs,
            ci = m.cost.input,
            co = m.cost.output,
            cr = m.cost.cache_read,
            cw = m.cost.cache_write,
            ctx = m.context_window,
            max = m.max_tokens,
            fat = opt_bool(m.compat.force_adaptive_thinking),
            st = opt_bool(m.compat.supports_temperature),
        )
        .unwrap();
    }
    out.push_str("    ]\n}\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("models_generated.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}
